version: '2.1'

services:
  pdf-signature-verifier:
    image: robol/pdfsignatureverifier
    volumes:
      - ./certs:/certs

  nginx:
    image: nginx
    volumes:
      - ./frontend/html:/frontend
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80

  
